"""
Django settings for ECHOME project.
Generated by 'django-admin startproject'.
"""

from pathlib import Path

import os

from dotenv import load_dotenv

import dj_database_url

# -----------------------------------------
# BASE DIR & ENVIRONMENT VARIABLES
# -----------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=env_path, override=True)

# Django secret key
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-default-key")

# Debug mode
DEBUG = os.getenv("DEBUG", "False") == "True"


# Allowed hosts
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS")
custom_host = os.getenv("CUSTOM_HOST")

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    f"{custom_host}",
]


# -----------------------------------------
# BLOCKCHAIN CONFIG
# -----------------------------------------
PRIVATE_KEY = os.getenv("PRIVATE_KEY")
WALLET_ADDRESS = os.getenv("WALLET_ADDRESS")
RPC_ENDPOINT = os.getenv("RPC_URL")
CONTRACT_ADDRESS = os.getenv("CONTRACT_ADDRESS")
CHAIN_ID = os.getenv("CHAIN_ID")

# -----------------------------------------
# FILEBASE / STORAGE CONFIG
# -----------------------------------------
FILEBASE_KEY = os.getenv("FILEBASE_KEY")
FILEBASE_SECRET = os.getenv("FILEBASE_SECRET")
BUCKET_NAME = os.getenv("BUCKET_NAME")

# -----------------------------------------
# SMTP EMAIL CONFIG (GMAIL )
# -----------------------------------------
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"  # prints emails in console
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@example.com")

GMAIL_PASSWORD = os.getenv("GMAIL_PASSWORD")  


# APPLICATIONS

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # definded apps
    "accounts",     # custom User model + auth
    "worker",
    "ECHOME",
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# MIDDLEWARE

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',   #
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'accounts.middleware.CustomAuthMiddleware', # my cutome auth middleware 


]

ROOT_URLCONF = "ECHOME.urls"


# TEMPLATES

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "ECHOME.wsgi.application"


# DATABASE
#automatic db engine selection based on db url

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DB_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# -----------------------------------------
# AUTHENTICATION & CUSTOM USER MODEL
# -----------------------------------------


AUTH_USER_MODEL = "accounts.User"


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "accounts.auth_backend.EmailOrUsernameBackend"
]


ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"   
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_FORMS = {
    "signup": "accounts.forms.CustomSignupForm"
}

# -----------------------------------------
# PASSWORD VALIDATORS
# -----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# -----------------------------------------
# STATIC FILES
# -----------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"




# loggging 

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "project.log",
            "formatter": "standard",
        },
    },

    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}


# -----------------------------------------
# SECURITY 
# -----------------------------------------
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = False
X_FRAME_OPTIONS = "DENY"

# Celery / Redis
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")

# Optional: json serialization to avoid pickle
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Beat schedule — run send_notification every 60 seconds
# from celery.schedules import crontab


CELERY_BEAT_SCHEDULE = {
    "check-expired-capsules-every-1-min": {
        "task": "worker.tasks.run_send_notification",
        "schedule": 60.0,
    },
}

LOGIN_URL = 'account:login'
LOGIN_REDIRECT_URL = 'homepage'
LOGOUT_REDIRECT_URL = 'account:login'


# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         },
#         'APP': {
#             'client_id':os.getenv("GOOGLE_CLIENT_ID"),
#             'secret':os.getenv("GOOGLE_CLIENT_SECRET"),
#             'key': ""
#         }
#     }
# }


# cookie and session settings


SESSION_SECRET_KEY = os.getenv("SESSION_SECRET_KEY")
SESSION_COOKIE_NAME ="XSESSIONID"
CUSTOM_SESSION_COOKIE = SESSION_COOKIE_NAME
SESSION_TTL_SECONDS = 7 * 24 * 3600  # 7 days


MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"
